### ISSUE TITLE
Demo and codesandbox page 'TodoFacade' is not exported from 'todo-list'.

### ISSUE THREAD

**Issue by senpl** [koshuang/react-todo#1]
App not start as expected.
```
./src/modules/todo-list/components/TodoDashboard.tsx
Attempted import error: 'TodoFacade' is not exported from 'todo-list'.
```

**Comment by koshuang** [comment]
@senpl thanks for your feedback. There is somehow an bug on codesandbox page I think. So I have deployed code to zeit.co. The new demo site is https://react-todo.koshuang.now.sh.
